[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
    "cd ai-learning",
    "rm -rf node_modules package-lock.json",
    "npm install"
]

[phases.build]
cmds = [
    "cd ai-learning",
    "npm run build"
]

[start]
cmd = "npx serve -s ai-learning/dist -l 3000"