[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["echo 'Iniciando fase de instalación...'"]

[phases.build]
cmds = [
    "rm -rf ai-learning/node_modules ai-learning/package-lock.json",
    "npm install --prefix ai-learning --force",
    "npm run build --prefix ai-learning"
]

[start]
cmd = "npx serve -s ai-learning/dist -l 3000"